title: Hao Zhang
position: Ph.D. Student
affiliation: Nanjing University of Aeronautics and Astronautics
affi: NUAA
email: haozhangcn@nuaa.edu.cn
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=zs9DkEAAAAAJ&hl=en
github_link: https://github.com/haozhangcn
researchgate: https://www.researchgate.net/profile/Hao-Zhang-408
cv: ./file/haozhang.pdf
orcid: https://orcid.org/0000-0003-1923-589X
publons: https://publons.com/researcher/3847741/hao-zhang/
avatar: ./assets/img/haozhang.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/haozhang.jpg
favicon_dark: ./assets/img/haozhang.jpg
description: Academic personal homepage for haozhangcn.com.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
